adding stats testcases
open-traffic-generator/ixnetwork pull request #159
Opened 2020-12-14 05:29 UTC by ANISH-GOTTAPU

adding stats testcases for #123,#124,#140,#141

2020-12-14 09:22 UTC, ashutshkumr commented
@ANISH-GOTTAPU please check if build failures are legitimate. If it's expected, please skip mark them as e2e unless the underlying issue is fixed.

2020-12-14 12:13 UTC, ANISH-GOTTAPU commented
@Rangababu-R & @ashutshkumr Not able to get why this is failing in CI/CD setup, if port stats are matched then flow stats also should match properly. Can you pull and check in your setup once
<b>Local</b>
Fetching all port stats ...
Fetching all flow stats ...

Port Stats
-----------------------------------------------------------------------------------------------
           Port      Tx Frames       Tx Bytes      Rx Frames       Rx Bytes         Tx FPS
         raw_tx           3000        3074000              0              0            0.0
         raw_rx              0              0           3000        3074000            0.0
-----------------------------------------------------------------------------------------------


Flow Stats
--------------------------------------------------
           Flow      Rx Frames       Rx Bytes
             f1           1000          74000
             f2           2000        3000000
--------------------------------------------------


<b>CI/CD flow</b>

Fetching all port stats ...
Fetching all flow stats ...

Port Stats
-----------------------------------------------------------------------------------------------
           Port      Tx Frames       Tx Bytes      Rx Frames       Rx Bytes         Tx FPS
         raw_tx           3000        3074000              0              0            0.0
         raw_rx              0              0           3000        3074000            0.0
-----------------------------------------------------------------------------------------------


Flow Stats
--------------------------------------------------
           Flow      Rx Frames       Rx Bytes
             f2           2000        3000000
             f1              0              0
--------------------------------------------------

2020-12-14 12:53 UTC, ashutshkumr commented
Maybe something wrong with calculation ? From logs I see this

```
        for row in flow_results:
            if row['name'] == 'f1':
                if column_name == 'frames_tx':
                    assert row[column_name] == f1_packets
                elif column_name == 'frames_rx':
>                   assert row[column_name] == f1_packets
E                   assert 0 == 1000
E                     -0
E                     +1000

```

2020-12-14 13:04 UTC, ANISH-GOTTAPU commented
Yes the flow stats on f1 should be 1000, not sure why 0 is returned. f1(1000) & f2(2000) , total 3000 are showing in port stats but same is not reflecting in flow stats of f1. But same is working in local with python2 & python3

2020-12-21 07:39 UTC, ashutshkumr commented on tests/statistics/test_port_and_flow_stats.py
> +    flow1.packet = [
no need to add header here

2020-12-21 07:40 UTC, ashutshkumr commented on tests/statistics/test_port_and_flow_stats.py
> +
Poll for stats to be as expected to signal that we have all required data available for validation. Do not use tolerance value.

2020-12-21 07:41 UTC, ashutshkumr commented on tests/statistics/test_port_and_flow_stats.py
> +    tolerance = 10
remove tolerance, and simplify assertions

2020-12-21 07:42 UTC, ashutshkumr commented on tests/statistics/test_port_and_flow_stats_e2e.py
> +    flow1.packet = [
remove headers

2020-12-21 07:44 UTC, ashutshkumr commented on tests/statistics/test_port_and_flow_stats.py
> +@pytest.mark.e2e
don't skip tests by tagging it as e2e. use something like:
```python
@pytest.mark.skip(reason="Reason for skip")
```

2020-12-21 07:46 UTC, ashutshkumr requested changes
Please address all review comments.

2020-12-21 13:20 UTC, ashutshkumr approved these changes

2020-12-21 13:21 UTC, merged